CREATE DATABASE IF NOT EXISTS ecommerce_interview;
USE ecommerce_interview;

CREATE TABLE customers (
    customer_id INT PRIMARY KEY,
    customer_name VARCHAR(100) NOT NULL,
    city VARCHAR(50),
    country VARCHAR(50),
    signup_date DATE
);
select * from customers;

CREATE TABLE products (
    product_id INT PRIMARY KEY,
    product_name VARCHAR(100) NOT NULL,
    category VARCHAR(50),
    price DECIMAL(10,2) NOT NULL,
    stock INT DEFAULT 0
);
select * from products;
CREATE TABLE orders (
    order_id INT PRIMARY KEY,
    customer_id INT NOT NULL,
    order_date DATE NOT NULL,
    status VARCHAR(30),
    payment_method VARCHAR(30),

    FOREIGN KEY (customer_id)
    REFERENCES customers(customer_id)
);
select * from orders;

CREATE TABLE order_items (
    order_item_id INT PRIMARY KEY,
    order_id INT NOT NULL,
    product_id INT NOT NULL,
    quantity INT NOT NULL,
    unit_price DECIMAL(10,2) NOT NULL,

    FOREIGN KEY (order_id)
    REFERENCES orders(order_id),

    FOREIGN KEY (product_id)
    REFERENCES products(product_id)
);
select * from order_items;

-- show all the records where price is greater than 100000 from products 













-- Q1. Show all customers from Bengaluru.
select * from customers where city = 'Bengaluru';

-- Show customers who signed up after ‘2025-01-01’.
select * from customers where signup_date > '2025-01-01' ;

-- Q3. Find customers from Mumbai and Hyderabad.
select * from customers where city = 'Mumbai' and 'Hyderabad';

-- Q4. Show products belonging to the Electronics category.
select * from products where category= 'Electronics';

-- Q5. Find products priced above 40000.
select * from products where price > 40000;

-- Q6. Show products where stock is less than 20.
select * from products where stock < 20 ;

-- Q7. Find products with stock between 50 and 100.
select * from products where stock between 50 and 100 ;

-- Q8. Show customers whose names start with ‘A’.
select * from customers where customer_name like 'A%';

-- Q9. Find products whose names contain ‘Premium’.
select * from products where product_name like '%Premium%';

-- Q10. Show customers registered during the year 2025.
select * from customers where year(signup_date) = 2025;


-- PART 2: Revenue & Sales Analysis
-- Business Requirement: The finance department wants summarized revenue and sales insights.
-- Q11. Find total revenue generated by each category.
select category,sum(price) as revenue from products
group by category
order by revenue desc
limit 5;

-- Q12. Find total quantity sold for each product.
select product_id,sum(quantity) as total_quantity from order_items
group by product_id;
-- Q13. Find total orders under each order status
select count(order_id) as total_orders ,status from orders 
group by status ;

-- Q14. Find total revenue generated through each payment method.
select o.payment_method, sum(p.price) as revenue from orders o 
join order_items oi on oi.order_id = o.order_id
join products p on p.product_id = oi.product_id 
group by o.payment_method;

-- Q15. Find average product price category-wise.
select category,avg(price) as average_products
 from products
group by category;

-- Q16. Find category-wise quantity sold.
select p.category,count(oi.quantity) as quantity_sold from products p
join order_items oi on p.product_id = oi.product_id
group by p.category;

-- Q17. Find monthly order count.
select count(order_id),date_format(order_date,'%M') as month from orders
group by month, month(order_date)
order by month(order_date);


-- Q18. Find monthly revenue trend.
select oi.product_id,oi.order_id,count(oi.quantity*oi.unit_price) as revenue , date_format(o.order_date,'%M')  as month from order_items oi
join orders o on oi.order_id = o.order_id
group by oi.product_id,oi.order_id,month,month(o.order_date)
order by month(o.order_date);


-- Q19. Find the most commonly used payment method.
-- Q20. Find the highest revenue-generating category.

-- PART 3: High-Value Business Insights
-- Business Requirement: Management wants to identify high-performing customers, products, and regions.
-- Q21. Find customers who placed more than 5 orders.
SELECT 
    c.customer_id,
    COUNT(o.order_id) AS total_orders  
FROM customers c  
JOIN orders o ON c.customer_id = o.customer_id 
GROUP BY c.customer_id
HAVING COUNT(o.order_id) > 5; 

-- Q22. Find top 5 customers based on total spending.

SELECT 
    c.customer_id,
    c.customer_name,
    SUM(oi.quantity * oi.unit_price) AS total_spending
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
GROUP BY c.customer_id, c.customer_name
ORDER BY total_spending DESC
LIMIT 5;

-- Q23. Find products sold more than 30 times.

SELECT 
    p.product_id,
    p.product_name,
    SUM(oi.quantity) AS total_quantity_sold
FROM products p
JOIN order_items oi
    ON p.product_id = oi.product_id
GROUP BY p.product_id, p.product_name
HAVING SUM(oi.quantity) > 30;

-- Q24. Find categories generating revenue greater than 500000.

SELECT 
    p.category,
    SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM products p
JOIN order_items oi
    ON p.product_id = oi.product_id
GROUP BY p.category
HAVING SUM(oi.quantity * oi.unit_price) > 500000;

-- Q25. Find cities having more than 10 customers.

SELECT 
    city,
    COUNT(customer_id) AS total_customers
FROM customers
GROUP BY city
HAVING COUNT(customer_id) > 10;

-- Q26. Find the top 5 highest-selling products.

SELECT 
    p.product_id,
    p.product_name,
    SUM(oi.quantity) AS total_sold
FROM products p
JOIN order_items oi
    ON p.product_id = oi.product_id
GROUP BY p.product_id, p.product_name
ORDER BY total_sold DESC
LIMIT 5;

-- Q27. Find the top 3 most profitable products.

SELECT 
    p.product_id,
    p.product_name,
    SUM(oi.quantity * oi.unit_price) AS total_profit
FROM products p
JOIN order_items oi
    ON p.product_id = oi.product_id
GROUP BY p.product_id, p.product_name
ORDER BY total_profit DESC
LIMIT 3;

-- Q28. Find customers whose spending is above average customer spending.

SELECT 
    customer_id,
    customer_name,
    total_spending
FROM
(
    SELECT 
        c.customer_id,
        c.customer_name,
        SUM(oi.quantity * oi.unit_price) AS total_spending
    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
    JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY c.customer_id, c.customer_name
) customer_spending
WHERE total_spending >
(
    SELECT AVG(total_spending)
    FROM
    (
        SELECT 
            SUM(oi.quantity * oi.unit_price) AS total_spending
        FROM orders o
        JOIN order_items oi
            ON o.order_id = oi.order_id
        GROUP BY o.customer_id
    ) avg_spending
);

-- Q29. Find products contributing more than 10% of company revenue.

SELECT 
    p.product_id,
    p.product_name,
    SUM(oi.quantity * oi.unit_price) AS product_revenue
FROM products p
JOIN order_items oi
    ON p.product_id = oi.product_id
GROUP BY p.product_id, p.product_name
HAVING SUM(oi.quantity * oi.unit_price) >
(
    SELECT SUM(quantity * unit_price) * 0.10
    FROM order_items
);

-- Q30. Find the city generating the highest revenue.

SELECT 
    c.city,
    SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
GROUP BY c.city
ORDER BY total_revenue DESC
LIMIT 1;


-- PART 4: Customer & Product Intelligence
-- Business Requirement: The CRM and product teams want detailed operational insights.
-- Q31. Display all orders along with customer names.
select o.*, c.customer_name from orders o
join customers c on o.customer_id = c.customer_id
order by order_id;

-- Q32. Find total revenue generated by each customer.
select c.customer_id,c.customer_name,sum(quantity*unit_price)as revenue from customers c
join orders o on c.customer_id=o.customer_id
join order_items oi on o.order_id=oi.order_id
group by c.customer_id,c.customer_name;
-- Q33. Find total number of orders placed by each customer.
select c.customer_id, count(o.order_id) as total_orders from orders o
join customers  c on o.customer_id = c.customer_id
group by c.customer_id;
-- Q34. Find customers who never placed any orders.
select c.customer_id from customers c
left join orders o on c.customer_id = o.customer_id
where o.order_id is null;
-- Q35. Find the latest order date for each customer.
select c.customer_id,c.customer_name,max(o.order_date) as o_date from customers c
join orders o on c.customer_id = o.customer_id
group by c.customer_id,c.customer_name;

-- Q36. Find product-wise revenue generated.
select *, sum(price) as revenue from products
group by product_id;
-- Q37. Find products that were never sold.
select p.product_id,p.product_name from products p 
left join order_items oi on p.product_id= oi.product_id
where oi.product_id is null;

-- Q38. Find products whose stock is lower than total quantity sold.
select p.product_name,p.stock ,sum(oi.quantity)as total_quantity from products p
join order_items oi
on p.product_id = oi.product_id
group by product_name,p.stock
having stock< total_quantity
order by total_quantity desc
limit 5;

-- Q39. Find category-wise revenue contribution percentage.
select p.category, sum(quantity*unit_price)*0.01 as percent  from products p
join order_items oi on p.product_id = oi.product_id 
group by p.category;


-- Q40. Find repeat customers who ordered in multiple months
select c.customer_id,c.customer_name, count(month(o.order_date)) as months from customers c
join orders o on c.customer_id = o.customer_id
group by c.customer_id,c.customer_name;

-- PART 5: Executive-Level Analytics
-- Business Requirement: The leadership team wants strategic business KPIs for decision-making.
-- Q41. Calculate overall company revenue.

SELECT 
    SUM(quantity * unit_price) AS overall_revenue
FROM order_items;

-- Q42. Calculate average order value.

SELECT 
    AVG(order_total) AS average_order_value
FROM
(
    SELECT 
        o.order_id,
        SUM(oi.quantity * oi.unit_price) AS order_total
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY o.order_id
) order_values;

-- Q43. Calculate cancelled order percentage.

SELECT 
    ROUND(
        (COUNT(CASE WHEN status = 'Cancelled' THEN 1 END) * 100.0)
        / COUNT(*),
        2
    ) AS cancelled_order_percentage
FROM orders;

-- Q44. Find the month with highest revenue.

SELECT 
    MONTH(order_date) AS month_no,
    SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM orders o
JOIN order_items oi
    ON o.order_id = oi.order_id
GROUP BY MONTH(order_date)
ORDER BY total_revenue DESC
LIMIT 1;

-- Q45. Find the month with highest order volume.

SELECT 
    MONTH(order_date) AS month_no,
    COUNT(order_id) AS total_orders
FROM orders
GROUP BY MONTH(order_date)
ORDER BY total_orders DESC
LIMIT 1;

-- Q46. Find the most common order status.

SELECT 
    status,
    COUNT(*) AS total_orders
FROM orders
GROUP BY status
ORDER BY total_orders DESC
LIMIT 1;

-- Q47. Generate a payment-method-wise revenue report.

SELECT 
    o.payment_method,
    SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM orders o
JOIN order_items oi
    ON o.order_id = oi.order_id
GROUP BY o.payment_method
ORDER BY total_revenue DESC;

-- Q48. Generate a category-wise business summary report.

SELECT 
    p.category,
    COUNT(DISTINCT p.product_id) AS total_products,
    SUM(oi.quantity) AS total_units_sold,
    SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM products p
JOIN order_items oi
    ON p.product_id = oi.product_id
GROUP BY p.category
ORDER BY total_revenue DESC;

-- Q49. Generate a city-wise customer and revenue report.

SELECT 
    c.city,
    COUNT(DISTINCT c.customer_id) AS total_customers,
    SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
GROUP BY c.city
ORDER BY total_revenue DESC;

-- Q50. Generate a final executive sales report containing:
-- Total Revenue
-- Total Orders
-- Total Customers
-- Total Products Sold
-- Average Order Value

SELECT 
    (SELECT SUM(quantity * unit_price)
     FROM order_items) AS total_revenue,

    (SELECT COUNT(*)
     FROM orders) AS total_orders,

    (SELECT COUNT(*)
     FROM customers) AS total_customers,

    (SELECT SUM(quantity)
     FROM order_items) AS total_products_sold,

    (SELECT AVG(order_total)
     FROM
     (
         SELECT 
             o.order_id,
             SUM(oi.quantity * oi.unit_price) AS order_total
         FROM orders o
         JOIN order_items oi
             ON o.order_id = oi.order_id
         GROUP BY o.order_id
     ) avg_orders
    ) AS average_order_value;