CREATE DATABASE IF NOT EXISTS ecommerce_interview;
USE ecommerce_interview;

CREATE TABLE customers (
    customer_id INT PRIMARY KEY,
    customer_name VARCHAR(100) NOT NULL,
    city VARCHAR(50),
    country VARCHAR(50),
    signup_date DATE
);
select * from customers;

CREATE TABLE products (
    product_id INT PRIMARY KEY,
    product_name VARCHAR(100) NOT NULL,
    category VARCHAR(50),
    price DECIMAL(10,2) NOT NULL,
    stock INT DEFAULT 0
);
select * from products;
CREATE TABLE orders (
    order_id INT PRIMARY KEY,
    customer_id INT NOT NULL,
    order_date DATE NOT NULL,
    status VARCHAR(30),
    payment_method VARCHAR(30),

    FOREIGN KEY (customer_id)
    REFERENCES customers(customer_id)
);
select * from orders;

CREATE TABLE order_items (
    order_item_id INT PRIMARY KEY,
    order_id INT NOT NULL,
    product_id INT NOT NULL,
    quantity INT NOT NULL,
    unit_price DECIMAL(10,2) NOT NULL,

    FOREIGN KEY (order_id)
    REFERENCES orders(order_id),

    FOREIGN KEY (product_id)
    REFERENCES products(product_id)
);
select * from order_items;

-- show all the records where price is greater than 100000 from products 













-- Q1. Show all customers from Bengaluru.
select * from customers where city = 'Bengaluru';

-- Show customers who signed up after ‘2025-01-01’.
select * from customers where signup_date > '2025-01-01' ;

-- Q3. Find customers from Mumbai and Hyderabad.
select * from customers where city = 'Mumbai' and 'Hyderabad';

-- Q4. Show products belonging to the Electronics category.
select * from products where category= 'Electronics';

-- Q5. Find products priced above 40000.
select * from products where price > 40000;

-- Q6. Show products where stock is less than 20.
select * from products where stock < 20 ;

-- Q7. Find products with stock between 50 and 100.
select * from products where stock between 50 and 100 ;

-- Q8. Show customers whose names start with ‘A’.
select * from customers where customer_name like 'A%';

-- Q9. Find products whose names contain ‘Premium’.
select * from products where product_name like '%Premium%';

-- Q10. Show customers registered during the year 2025.
select * from customers where year(signup_date) = 2025;


-- PART 2: Revenue & Sales Analysis
-- Business Requirement: The finance department wants summarized revenue and sales insights.
-- Q11. Find total revenue generated by each category.
select category,sum(price) as revenue from products
group by category
order by revenue desc
limit 5;

-- Q12. Find total quantity sold for each product.
select product_id,sum(quantity) as total_quantity from order_items
group by product_id;
-- Q13. Find total orders under each order status
select count(order_id) as total_orders ,status from orders 
group by status ;

-- Q14. Find total revenue generated through each payment method.
select o.payment_method, sum(p.price) as revenue from orders o 
join order_items oi on oi.order_id = o.order_id
join products p on p.product_id = oi.product_id 
group by o.payment_method;

-- Q15. Find average product price category-wise.
select category,avg(price) as average_products
 from products
group by category;

-- Q16. Find category-wise quantity sold.
select p.category,count(oi.quantity) as quantity_sold from products p
join order_items oi on p.product_id = oi.product_id
group by p.category;

-- Q17. Find monthly order count.
select count(order_id),date_format(order_date,'%M') as month from orders
group by month
order by month;


-- Q18. Find monthly revenue trend.


-- Q19. Find the most commonly used payment method.
-- Q20. Find the highest revenue-generating category.

-- PART 3: High-Value Business Insights
-- Business Requirement: Management wants to identify high-performing customers, products, and regions.
-- Q21. Find customers who placed more than 5 orders.
-- Q22. Find top 5 customers based on total spending.
-- Q23. Find products sold more than 30 times.
-- Q24. Find categories generating revenue greater than 500000.
-- Q25. Find cities having more than 10 customers.
-- Q26. Find the top 5 highest-selling products.
-- Q27. Find the top 3 most profitable products.
-- Q28. Find customers whose spending is above average customer spending.
-- Q29. Find products contributing more than 10% of company revenue.
-- Q30. Find the city generating the highest revenue.


-- 
